<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9H86UB9" failures="1" tests="6" name="com.POS.Testcases.VerifyStoreTest" time="77.310" errors="0" timestamp="2023-03-16T22:26:18 GST" skipped="1">
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateShowCount" time="14.185"/>
  <system-out/>
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateAddStore" time="13.775"/>
  <system-out/>
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateSearchStore" time="12.037"/>
  <system-out/>
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateEditStore" time="15.261"/>
  <system-out/>
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateStoreSorting" time="22.052">
    <failure message="The following asserts failed:
	expected [VKS Store2147483647] but found [AJStores]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [VKS Store2147483647] but found [AJStores]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.POS.Testcases.VerifyStoreTest.validateStoreSorting(VerifyStoreTest.java:141)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateStoreSorting -->
  <system-out/>
  <testcase classname="com.POS.Testcases.VerifyStoreTest" name="validateTableHeaders">
    <skipped/>
  </testcase> <!-- validateTableHeaders -->
  <system-out/>
</testsuite> <!-- com.POS.Testcases.VerifyStoreTest -->
